# Generated by Django 5.0.1 on 2026-02-01 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], max_length=20)),
                ('prompt', models.TextField(help_text="User's original prompt")),
                ('generated_text', models.TextField()),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('humorous', 'Humorous'), ('inspirational', 'Inspirational'), ('educational', 'Educational')], max_length=20)),
                ('audience', models.CharField(blank=True, max_length=100)),
                ('ai_provider', models.CharField(default='openai', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('generated_text', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
