# Generated by Django 5.0.1 on 2026-02-01 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='content',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='organizations.workspace'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.content'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['organization', 'status'], name='contents_organiz_b44bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['created_by'], name='contents_created_fb3de2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('content', 'version_number')},
        ),
    ]
