# Generated by Django 5.0.1 on 2026-02-01 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('job_id', models.CharField(blank=True, help_text='BullMQ job ID from Node.js', max_length=255)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='content.content')),
            ],
            options={
                'db_table': 'scheduled_posts',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
