# Generated by Django 5.0.1 on 2026-02-01 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['organization', 'status'], name='scheduled_p_organiz_0c0978_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['scheduled_at'], name='scheduled_p_schedul_7cdbf3_idx'),
        ),
    ]
